const assetsPath = `../assets/images`;
export const ERROR = require(`${assetsPath}/cross.png`);
export const WARNING = require(`${assetsPath}/warning.png`);
export const SUCCESS = require(`${assetsPath}/success.png`);
export const LOADER = require(`${assetsPath}/loader.gif`);
export const MENUE = require(`${assetsPath}/menue.png`);
export const PROFILE = require(`${assetsPath}/profile.png`);
export const LOGO = require(`${assetsPath}/jigyasulogo.png`);
export const BACKGROUND = require(`${assetsPath}/background.png`);